Build unified EKS CI/CD pipeline

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -324,22 +324,6 @@ jobs:
           kubectl get service \
             -n "$NAMESPACE"
 
-      - name: Verify External Secrets
-        run: |
-          echo "=== SecretStore ==="
-          kubectl get secretstore \
-            -n "$NAMESPACE" \
-            -o wide
-
-          echo "=== ExternalSecrets ==="
-          kubectl get externalsecret \
-            -n "$NAMESPACE" \
-            -o wide
-
-          echo "=== Kubernetes Secrets ==="
-          kubectl get secrets \
-            -n "$NAMESPACE"
-
       - name: Wait for External Secrets
         run: |
           echo "Waiting for External Secrets to become Ready..."
@@ -358,12 +342,35 @@ jobs:
 
           echo "External Secrets are ready."
 
+      - name: Verify External Secrets
+        run: |
+          echo "=== SecretStore ==="
+          kubectl get secretstore \
+            -n "$NAMESPACE" \
+            -o wide
+
+          echo "=== ExternalSecrets ==="
+          kubectl get externalsecret \
+            -n "$NAMESPACE" \
+            -o wide
+
+          echo "=== Kubernetes Secrets ==="
+          kubectl get secrets \
+            -n "$NAMESPACE"
+
       - name: Wait for application rollout
         run: |
-          kubectl rollout status \
-            deployment/backend \
+          DEPLOYMENT=$(kubectl get deployments \
             -n "$NAMESPACE" \
-            --timeout=180s
+            -l "app.kubernetes.io/instance=backend" \
+            -o jsonpath='{.items[0].metadata.name}')
+
+          echo "Deployment found: $DEPLOYMENT"
+
+          kubectl rollout status \
+           deployment/"$DEPLOYMENT" \
+           -n "$NAMESPACE" \
+           --timeout=180s
 
       - name: Show application state
         run: |
@@ -427,19 +434,17 @@ jobs:
             if [ -n "$ALB" ]; then
               echo "ALB address: $ALB"
               echo "ALB_HOSTNAME=$ALB" >> "$GITHUB_ENV"
-              break
+              exit 0
             fi
 
-            echo "ALB not ready yet. Waiting..."
+            echo "Attempt $i/30: ALB not ready yet. Waiting..."
             sleep 10
 
           done
 
-          if [ -z "$ALB_HOSTNAME" ]; then
-            echo "ERROR: ALB hostname was not created."
-            kubectl get ingress -n "$NAMESPACE"
-            exit 1
-          fi
+          echo "ERROR: ALB hostname was not created."
+          kubectl get ingress -n "$NAMESPACE"
+          exit 1
 
       - name: Test application
         run: |
